name: Read Hello File

on:
  push:
    branches:
      - main  

jobs:
  read_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  

      - name: Read the File
        run: cat hello.txt 